runtime: custom
env: flex

# Konfigurasi Resource (Model AI berat butuh RAM minimal 4-8GB)
resources:
  cpu: 2
  memory_gb: 8
  disk_size_gb: 20

# Scaling otomatis (Start dengan 1 instance biar hemat)
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

# Environment variables
env_variables:
  STREAMLIT_SERVER_PORT: 8080